import Navbar from "@/components/DashboardLayout/navbar";
import { Sidebar } from "@/components/DashboardLayout/sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Sidebar />
        <header className="hidden sm:block">
          <Navbar />
        </header>
        <main className='mx-2 mt-16 sm:ml-[300px] sm:mt-3'>
          {children}
        </main>
      </body>
    </html>
  );
}