import Navbar from "@/components/DashboardLayout/navbar";
import { Sidebar } from "@/components/DashboardLayout/sidebar";
import type { Metadata } from "next";
import Provider from "../../context/Provider";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <Provider> 
        <Sidebar />
        <div className='flex flex-col h-full mr-2 mt-16 sm:ml-[280px] sm:mt-3 gap-2'>
          <div className="hidden sm:block">
            <Navbar />
          </div>
          <div className="h-45 rounded-xl p-4 flex-grow flex-1">
           {children}
          </div>
        </div>
      </Provider>
  );
}